# Generated by Django 4.1.7 on 2023-03-03 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Goldman Sachs', 'Goldman Sachs')], max_length=255, unique=True)),
                ('category', models.CharField(choices=[('INVESTMENT_BANKING', 'Investment Banking'), ('PRIVATE_EQUITY', 'Private Equity'), ('HEDGE_FUND', 'Hedge Fund'), ('ASSET_MANAGEMENT', 'Asset Management'), ('BULGE_BRACKET', 'Bulge Bracket'), ('INVESTMENT_FIRM', 'Investment Firm'), ('OTHER', 'Other')], max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('deadline_text', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=255, null=True)),
                ('program_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('cities', models.JSONField(blank=True, null=True)),
                ('is_application_open', models.BooleanField()),
                ('url', models.URLField(blank=True, null=True)),
                ('is_details_scraped', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.CharField(choices=[('SUMMER', 'Summer'), ('OFFCYCLE', 'Off-Cycle'), ('INSIGHT', 'Insight'), ('OTHER', 'Other')], default='Other', max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.company')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Program',
                'verbose_name_plural': 'User(s) Programs',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.region'),
        ),
    ]
