# Generated by Django 4.1.7 on 2023-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_userprogrampreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogrampreferences',
            name='company_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprogrampreferences',
            name='program_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprogrampreferences',
            name='regions',
            field=models.JSONField(default=list),
        ),
    ]
