# Generated by Django 4.1.7 on 2023-03-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_useremailnotificationpreferences_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogram',
            name='application_close_reason',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='does_ask_for_cover_letter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_application_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_application_submitted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_online_test_taken',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_personal_interview_taken',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_pre_recorded_video_interview_taken',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='online_test_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='personal_interview_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='pre_recorded_video_interview_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
