# Generated by Django 4.1.7 on 2023-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_userprogram_application_close_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogram',
            name='was_there_no_online_test',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='was_there_no_pre_recorded_video_interview_stage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
