# Generated by Django 4.1.7 on 2023-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_userprogram_was_there_no_online_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('Goldman Sachs', 'Goldman Sachs'), ('Morgan Stanley', 'Morgan Stanley')], max_length=255, unique=True),
        ),
    ]
