# Generated by Django 4.1.7 on 2023-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
