# Generated by Django 4.1.7 on 2023-03-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_program_application_url_program_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JPMorganProgramSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpmorgan_program_id', models.PositiveBigIntegerField()),
                ('url', models.URLField()),
                ('application_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=255, null=True)),
                ('program_type_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('Goldman Sachs', 'Goldman Sachs'), ('Morgan Stanley', 'Morgan Stanley'), ('JP Morgan', 'Jp Morgan')], max_length=255, unique=True),
        ),
    ]
