# Generated by Django 4.1.7 on 2023-03-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0011_jpmorganprogramsummary_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jpmorganprogramsummary',
            name='program_type_description',
        ),
        migrations.AddField(
            model_name='jpmorganprogramsummary',
            name='cities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jpmorganprogramsummary',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jpmorganprogramsummary',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.region'),
        ),
    ]
