# Generated by Django 4.1.7 on 2023-03-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_remove_jpmorganprogramsummary_program_type_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpmorganprogramsummary',
            name='jpmorgan_program_id',
            field=models.CharField(max_length=20),
        ),
    ]
