# Generated by Django 4.1.7 on 2023-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0013_alter_jpmorganprogramsummary_jpmorgan_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpmorganprogramsummary',
            name='is_copied_to_main_table',
            field=models.BooleanField(default=False),
        ),
    ]
