# Generated by Django 4.1.7 on 2023-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0015_alter_company_name_alter_program_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('Goldman Sachs', 'Goldman Sachs'), ('Morgan Stanley', 'Morgan Stanley'), ('JP Morgan', 'Jp Morgan'), ('Evercore', 'Evercore'), ('Lazard', 'Lazard'), ('Bank of America', 'Bank Of America')], max_length=255, unique=True),
        ),
    ]
