# Generated by Django 4.1.7 on 2023-03-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_program_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='application_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
