# Generated by Django 4.1.7 on 2023-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_alter_program_application_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
