# Generated by Django 4.1.7 on 2023-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0019_alter_program_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('BOUTIQUE', 'Boutique'), ('BANK', 'Bank')], max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('OFFCYCLE', 'Off-Cycle'), ('INSIGHT', 'Spring Week'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
