# Generated by Django 4.1.7 on 2023-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0020_alter_company_category_alter_program_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='found_in_latest_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
