# Generated by Django 4.1.7 on 2023-04-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0024_program_cities_mapped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JPMorganProgramSummary',
        ),
    ]
