# Generated by Django 4.1.7 on 2023-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0026_program_countries_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
