# Generated by Django 4.1.7 on 2023-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0029_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('Goldman Sachs', 'Goldman Sachs'), ('Morgan Stanley', 'Morgan Stanley'), ('JP Morgan', 'Jp Morgan'), ('Evercore', 'Evercore'), ('Lazard', 'Lazard'), ('Bank of America', 'Bank Of America'), ('BNP Paribas', 'Bnp Paribas'), ('Societe Generale', 'Societe Generale'), ('Rothschild', 'Rothschild'), ('Barclays', 'Barclays'), ('HSBC', 'Hsbc')], max_length=255, unique=True),
        ),
    ]
