# Generated by Django 4.1.7 on 2023-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0032_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
