# Generated by Django 4.1.7 on 2023-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0034_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailnotificationpreferences',
            name='regions',
        ),
        migrations.AddField(
            model_name='useremailnotificationpreferences',
            name='regions',
            field=models.ManyToManyField(to='internships.region'),
        ),
    ]
