# Generated by Django 4.1.7 on 2023-05-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0035_remove_useremailnotificationpreferences_regions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailnotificationpreferences',
            name='regions',
        ),
        migrations.AddField(
            model_name='useremailnotificationpreferences',
            name='regions',
            field=models.JSONField(default=list),
        ),
    ]
