# Generated by Django 4.1.7 on 2023-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0036_remove_useremailnotificationpreferences_regions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_visa_sponsorship_provided',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
