# Generated by Django 4.1.7 on 2023-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0037_program_is_visa_sponsorship_provided'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_date', models.DateField(unique=True, verbose_name='Historical Date')),
                ('total_programs_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('open_programs_count', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
