# Generated by Django 4.1.7 on 2023-07-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0038_historicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogram',
            name='is_application_closed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_application_submitted_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_online_test_taken_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_personal_interview_taken_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogram',
            name='is_pre_recorded_video_interview_taken_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
