# Generated by Django 4.1.7 on 2023-07-01 09:48

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import migrations

sql='''
    ALTER TABLE internships_program ADD COLUMN search_vector_column tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(description,'')), 'A') ||
        setweight(to_tsvector('english', coalesce(program_type,'')), 'B') ||
        setweight(to_tsvector('english', coalesce(program_type_description,'')), 'B') ||
        setweight(to_tsvector('english', coalesce(eligibility,'')), 'C')
    ) STORED;
'''

reverse_sql = '''ALTER TABLE internships_program DROP COLUMN search_vector_column;'''


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0039_userprogram_is_application_closed_datetime_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql=reverse_sql,
            state_operations=[
                migrations.AddField(
                    model_name='program',
                    name='search_vector_column',
                    field=SearchVectorField(null=True),
                )
            ]
        ),
        migrations.AddIndex(
            model_name='program',
            index=GinIndex(
                fields=['search_vector_column'],
                name='internships_search__50ff4a_gin'
            ),
        ),
    ]
