# Generated by Django 4.1.7 on 2023-06-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('stripe_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stripe_amount_total', models.PositiveBigIntegerField()),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('stripe_subscription_starts_at', models.DateTimeField()),
                ('stripe_subscription_ends_at', models.DateTimeField()),
                ('stripe_subscription_plan_name', models.CharField(max_length=255)),
                ('stripe_subscription_plan_id', models.CharField(max_length=255)),
                ('stripe_subscription_product_id', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
