# Generated by Django 4.1.7 on 2023-06-27 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAutoFillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='middle name')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='middle name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('education1', models.TextField(blank=True, max_length=20, null=True, verbose_name='Education 1')),
                ('education2', models.TextField(blank=True, max_length=20, null=True, verbose_name='Education 2')),
                ('education3', models.TextField(blank=True, max_length=20, null=True, verbose_name='Education 3')),
                ('employment1', models.TextField(blank=True, max_length=20, null=True, verbose_name='Employment 1')),
                ('employment2', models.TextField(blank=True, max_length=20, null=True, verbose_name='Employment 2')),
                ('employment3', models.TextField(blank=True, max_length=20, null=True, verbose_name='Employment 3')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
