# Generated by Django 4.1.7 on 2023-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_userautofillprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userautofillprofile',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='email'),
        ),
    ]
