CITY_MAPPING = {
    'Ciudad Aut\u00f3noma de Buenos Aires': {'name': 'Buenos Aires', 'country': 'Argentina', 'region': 'AMERICAS'},
    'BUENOS AIRES': {'name': 'Buenos Aires', 'country': 'Argentina', 'region': 'AMERICAS'},

    'MELBOURNE': {'name': 'Melbourne', 'country': 'Australia', 'region': 'ASIA'},
    'SYDNEY': {'name': 'Sydney', 'country': 'Australia', 'region': 'ASIA'},

    'Antwerpen': {'name': 'Antwerp', 'country': 'Belgium', 'region': 'EMEA'},
    'Antwerp': {'name': 'Antwerp', 'country': 'Belgium', 'region': 'EMEA'},
    'Brabant Wallon': {'name': 'Brabant Wallon', 'country': 'Belgium', 'region': 'EMEA'},
    'BRUSSELS': {'name': 'Brussels', 'country': 'Belgium', 'region': 'EMEA'},
    'Bruxelles': {'name': 'Brussels', 'country': 'Belgium', 'region': 'EMEA'},
    'Charleroi': {'name': 'Charleroi', 'country': 'Belgium', 'region': 'EMEA'},
    'Ghent': {'name': 'Ghent', 'country': 'Belgium', 'region': 'EMEA'},
    'Hainaut': {'name': 'Hainaut', 'country': 'Belgium', 'region': 'EMEA'},
    'Hasselt': {'name': 'Hasselt', 'country': 'Belgium', 'region': 'EMEA'},
    'Kortrijk': {'name': 'Kortrijk', 'country': 'Belgium', 'region': 'EMEA'},
    'Liège': {'name': 'Liège', 'country': 'Belgium', 'region': 'EMEA'},
    'Mons': {'name': 'Mons', 'country': 'Belgium', 'region': 'EMEA'},
    'Oost-Vlaanderen': {'name': 'Oost-Vlaanderen', 'country': 'Belgium', 'region': 'EMEA'},
    'Roeselare': {'name': 'Roeselare', 'country': 'Belgium', 'region': 'EMEA'},
    'Vlaams-Brabant': {'name': 'Vlaams-Brabant', 'country': 'Belgium', 'region': 'EMEA'},
    'West-Vlaanderen': {'name': 'West-Vlaanderen', 'country': 'Belgium', 'region': 'EMEA'},

    'SAO PAULO': {'name': 'Sao Paulo', 'country': 'Brazil', 'region': 'AMERICAS'},
    'São Paulo': {'name': 'Sao Paulo', 'country': 'Brazil', 'region': 'AMERICAS'},

    'TORONTO': {'name': 'Toronto', 'country': 'Canada', 'region': 'AMERICAS'},
    'CALGARY': {'name': 'Calgary', 'country': 'Canada', 'region': 'AMERICAS'},
    'MONTREAL': {'name': 'Montreal', 'country': 'Canada', 'region': 'AMERICAS'},

    'SANTIAGO': {'name': 'Santiago', 'country': 'Chile', 'region': 'AMERICAS'},

    'BEIJING': {'name': 'Beijing', 'country': 'China', 'region': 'ASIA'},
    'HONG KONG': {'name': 'Hong Kong', 'country': 'China', 'region': 'ASIA'},
    'SHENZHEN': {'name': 'Shenzhen', 'country': 'China', 'region': 'ASIA'},

    'BOGOTA': {'name': 'Bogota', 'country': 'Colombia', 'region': 'AMERICAS'},

    'Agen': {'name': 'Agen', 'country': 'France', 'region': 'EMEA'},
    'Aix-En-Provence': {'name': 'Aix-En-Provence', 'country': 'France', 'region': 'EMEA'},
    'Altkirch': {'name': 'Altkirch', 'country': 'France', 'region': 'EMEA'},
    'Annecy': {'name': 'Annecy', 'country': 'France', 'region': 'EMEA'},
    'Annemasse': {'name': 'Annemasse', 'country': 'France', 'region': 'EMEA'},
    'Arras': {'name': 'Arras', 'country': 'France', 'region': 'EMEA'},
    'Auxerre': {'name': 'Auxerre', 'country': 'France', 'region': 'EMEA'},
    'Avignon': {'name': 'Avignon', 'country': 'France', 'region': 'EMEA'},
    'Besancon': {'name': 'Besancon', 'country': 'France', 'region': 'EMEA'},
    'Beziers': {'name': 'Beziers', 'country': 'France', 'region': 'EMEA'},
    'Biscarrosse': {'name': 'Biscarrosse', 'country': 'France', 'region': 'EMEA'},
    'Blois': {'name': 'Blois', 'country': 'France', 'region': 'EMEA'},
    'BORDEAUX': {'name': 'Bordeaux', 'country': 'France', 'region': 'EMEA'},
    'Boulogne-Billancourt': {'name': 'Boulogne-Billancourt', 'country': 'France', 'region': 'EMEA'},
    'Bourges': {'name': 'Bourges', 'country': 'France', 'region': 'EMEA'},
    'Brumath': {'name': 'Brumath', 'country': 'France', 'region': 'EMEA'},
    'Cannes': {'name': 'Cannes', 'country': 'France', 'region': 'EMEA'},
    'Capbreton': {'name': 'Capbreton', 'country': 'France', 'region': 'EMEA'},
    'Cergy': {'name': 'Cergy', 'country': 'France', 'region': 'EMEA'},
    'Cesson-Sevigne': {'name': 'Cesson-Sevigne', 'country': 'France', 'region': 'EMEA'},
    'Chalon-Sur-Saone': {'name': 'Chalon-Sur-Saone', 'country': 'France', 'region': 'EMEA'},
    'Chambery': {'name': 'Chambery', 'country': 'France', 'region': 'EMEA'},
    'Champagnole': {'name': 'Champagnole', 'country': 'France', 'region': 'EMEA'},
    'Chateauneuf-Sur-Loire': {'name': 'Chateauneuf-Sur-Loire', 'country': 'France', 'region': 'EMEA'},
    'Chateauroux': {'name': 'Chateauroux', 'country': 'France', 'region': 'EMEA'},
    'Chessy': {'name': 'Chessy', 'country': 'France', 'region': 'EMEA'},
    'Clermont-Ferrand': {'name': 'Clermont-Ferrand', 'country': 'France', 'region': 'EMEA'},
    'Clermont-Herault': {'name': 'Clermont-Herault', 'country': 'France', 'region': 'EMEA'},
    'Cognac': {'name': 'Cognac', 'country': 'France', 'region': 'EMEA'},
    'Colmar': {'name': 'Colmar', 'country': 'France', 'region': 'EMEA'},
    'Compiègne': {'name': 'Compiegne', 'country': 'France', 'region': 'EMEA'},
    'Compiegne': {'name': 'Compiegne', 'country': 'France', 'region': 'EMEA'},
    'Courbevoie': {'name': 'Courbevoie', 'country': 'France', 'region': 'EMEA'},
    'Dijon': {'name': 'Dijon', 'country': 'France', 'region': 'EMEA'},
    'Dunkerque': {'name': 'Dunkerque', 'country': 'France', 'region': 'EMEA'},
    'Ecully': {'name': 'Ecully', 'country': 'France', 'region': 'EMEA'},
    'Epinal': {'name': 'Epinal', 'country': 'France', 'region': 'EMEA'},
    'Evry': {'name': 'Evry', 'country': 'France', 'region': 'EMEA'},
    'Fontenay-Sous-Bois': {'name': 'Fontenay-Sous-Bois', 'country': 'France', 'region': 'EMEA'},
    'Forbach': {'name': 'Forbach', 'country': 'France', 'region': 'EMEA'},
    'Genas': {'name': 'Genas', 'country': 'France', 'region': 'EMEA'},
    'Goussainville': {'name': 'Goussainville', 'country': 'France', 'region': 'EMEA'},
    'Grand-Poitiers': {'name': 'Grand-Poitiers', 'country': 'France', 'region': 'EMEA'},
    'Grenoble': {'name': 'Grenoble', 'country': 'France', 'region': 'EMEA'},
    'Guebwiller': {'name': 'Guebwiller', 'country': 'France', 'region': 'EMEA'},
    'Hauts-de-France': {'name': 'Hauts-de-France', 'country': 'France', 'region': 'EMEA'},
    'Hérault': {'name': 'Hérault', 'country': 'France', 'region': 'EMEA'},
    'Île-de-France': {'name': 'Île-de-France', 'country': 'France', 'region': 'EMEA'},
    'Ille-et-Vilaine': {'name': 'Ille-et-Vilaine', 'country': 'France', 'region': 'EMEA'},
    'Issy-les-Moulineaux': {'name': 'Issy-les-Moulineaux', 'country': 'France', 'region': 'EMEA'},
    'Jacou': {'name': 'Jacou', 'country': 'France', 'region': 'EMEA'},
    "L'Isle-Jourdain": {'name': "L'Isle-Jourdain", 'country': 'France', 'region': 'EMEA'},
    'La-Roche-Sur-Yon': {'name': 'La-Roche-Sur-Yon', 'country': 'France', 'region': 'EMEA'},
    'La Defense': {'name': 'La Defense', 'country': 'France', 'region': 'EMEA'},
    'La-Plaine-Saint-Denis': {'name': 'La-Plaine-Saint-Denis', 'country': 'France', 'region': 'EMEA'},
    'Labege': {'name': 'Labege', 'country': 'France', 'region': 'EMEA'},
    'Laval': {'name': 'Laval', 'country': 'France', 'region': 'EMEA'},
    'Le-Plessis-Belleville': {'name': 'Le-Plessis-Belleville', 'country': 'France', 'region': 'EMEA'},
    'Lens': {'name': 'Lens', 'country': 'France', 'region': 'EMEA'},
    'Levallois-Perret': {'name': 'Levallois-Perret', 'country': 'France', 'region': 'EMEA'},
    'Lille': {'name': 'Lille', 'country': 'France', 'region': 'EMEA'},
    'Limoges': {'name': 'Limoges', 'country': 'France', 'region': 'EMEA'},
    'Loches': {'name': 'Loches', 'country': 'France', 'region': 'EMEA'},
    'Longjumeau': {'name': 'Longjumeau', 'country': 'France', 'region': 'EMEA'},
    'Louhans': {'name': 'Louhans', 'country': 'France', 'region': 'EMEA'},
    'LYON': {'name': 'Lyon', 'country': 'France', 'region': 'EMEA'},
    'Marcq-en-Barœul': {'name': 'Marcq-en-Barœul', 'country': 'France', 'region': 'EMEA'},
    'Marmande': {'name': 'Marmande', 'country': 'France', 'region': 'EMEA'},
    'Marseille': {'name': 'Marseille', 'country': 'France', 'region': 'EMEA'},
    'Massy': {'name': 'Massy', 'country': 'France', 'region': 'EMEA'},
    'Mérignac': {'name': 'Merignac', 'country': 'France', 'region': 'EMEA'},
    'Merignac': {'name': 'Mérignac', 'country': 'France', 'region': 'EMEA'},
    'Metz': {'name': 'Metz', 'country': 'France', 'region': 'EMEA'},
    'Meulan-En-Yvelines': {'name': 'Meulan-En-Yvelines', 'country': 'France', 'region': 'EMEA'},
    'Meximieux': {'name': 'Meximieux', 'country': 'France', 'region': 'EMEA'},
    'Mont-Saint-Aignan': {'name': 'Mont-Saint-Aignan', 'country': 'France', 'region': 'EMEA'},
    'Montargis': {'name': 'Montargis', 'country': 'France', 'region': 'EMEA'},
    'Montbeliard': {'name': 'Montbeliard', 'country': 'France', 'region': 'EMEA'},
    'Montivilliers': {'name': 'Montivilliers', 'country': 'France', 'region': 'EMEA'},
    'Montpellier': {'name': 'Montpellier', 'country': 'France', 'region': 'EMEA'},
    'Montreuil': {'name': 'Montreuil', 'country': 'France', 'region': 'EMEA'},
    'Morteau': {'name': 'Morteau', 'country': 'France', 'region': 'EMEA'},
    'Mulhouse': {'name': 'Mulhouse', 'country': 'Spain', 'region': 'EMEA'},
    'Nancy': {'name': 'Nancy', 'country': 'France', 'region': 'EMEA'},
    'Nanterre': {'name': 'Nanterre', 'country': 'France', 'region': 'EMEA'},
    'Nantes': {'name': 'Nantes', 'country': 'France', 'region': 'EMEA'},
    'Narbonne': {'name': 'Narbonne', 'country': 'France', 'region': 'EMEA'},
    'Nevers': {'name': 'Nevers', 'country': 'France', 'region': 'EMEA'},
    'Nice': {'name': 'Nice', 'country': 'France', 'region': 'EMEA'},
    'Noisy-le-Grand': {'name': 'Noisy-le-Grand', 'country': 'France', 'region': 'EMEA'},
    'Orleans': {'name': 'Orleans', 'country': 'France', 'region': 'EMEA'},
    'Orléans': {'name': 'Orleans', 'country': 'Spain', 'region': 'EMEA'},
    'Orsay': {'name': 'Orsay', 'country': 'France', 'region': 'EMEA'},
    'Palavas-Les-Flots': {'name': 'Palavas-Les-Flots', 'country': 'France', 'region': 'EMEA'},
    'Pantin': {'name': 'Pantin', 'country': 'France', 'region': 'EMEA'},
    'PARIS': {'name': 'Paris', 'country': 'France', 'region': 'EMEA'},
    'Pau': {'name': 'Pau', 'country': 'France', 'region': 'EMEA'},
    'Périgueux': {'name': 'Périgueux', 'country': 'France', 'region': 'EMEA'},
    'Poissy': {'name': 'Poissy', 'country': 'France', 'region': 'EMEA'},
    "Provence-Alpes-Côte d'Azur": {'name': 'Provence', 'country': 'France', 'region': 'EMEA'},
    'Puteaux': {'name': 'Puteaux', 'country': 'France', 'region': 'EMEA'},
    'Reims': {'name': 'Reims', 'country': 'France', 'region': 'EMEA'},
    'Rennes': {'name': 'Rennes', 'country': 'France', 'region': 'EMEA'},
    'Rodez': {'name': 'Rodez', 'country': 'France', 'region': 'EMEA'},
    'Rouen': {'name': 'Rouen', 'country': 'France', 'region': 'EMEA'},
    'Rueil-Malmaison': {'name': 'Rueil-Malmaison', 'country': 'France', 'region': 'EMEA'},
    'Rungis': {'name': 'Rungis', 'country': 'France', 'region': 'EMEA'},
    'Saint-Avold': {'name': 'Saint-Avold', 'country': 'France', 'region': 'EMEA'},
    'Saint-Denis': {'name': 'Saint-Denis', 'country': 'France', 'region': 'EMEA'},
    'Saint-Grégoire': {'name': 'Saint-Grégoire', 'country': 'France', 'region': 'EMEA'},
    'Saint-Jean-de-Luz': {'name': 'Saint-Jean-de-Luz', 'country': 'France', 'region': 'EMEA'},
    'St-Jean-Ruelle': {'name': 'St-Jean-Ruelle', 'country': 'France', 'region': 'EMEA'},
    'Saran': {'name': 'Saran', 'country': 'France', 'region': 'EMEA'},
    'Saverne': {'name': 'Saverne', 'country': 'France', 'region': 'EMEA'},
    'Schiltigheim': {'name': 'Schiltigheim', 'country': 'France', 'region': 'EMEA'},
    'Sotteville-lès-Rouen': {'name': 'Sotteville-lès-Rouen', 'country': 'France', 'region': 'EMEA'},
    'Strasbourg': {'name': 'Strasbourg', 'country': 'France', 'region': 'EMEA'},
    'Tarascon-Sur-Ariege': {'name': 'Tarascon-Sur-Ariege', 'country': 'France', 'region': 'EMEA'},
    'Tarbes': {'name': 'Tarbes', 'country': 'France', 'region': 'EMEA'},
    'Thionville': {'name': 'Thionville', 'country': 'France', 'region': 'EMEA'},
    'Toulon': {'name': 'Toulon', 'country': 'France', 'region': 'EMEA'},
    'Toulouse': {'name': 'Toulouse', 'country': 'France', 'region': 'EMEA'},
    'Tourcoing': {'name': 'Tourcoing', 'country': 'France', 'region': 'EMEA'},
    'Tours': {'name': 'Tours', 'country': 'France', 'region': 'EMEA'},
    'Valenciennes': {'name': 'Valenciennes', 'country': 'France', 'region': 'EMEA'},
    'Vendome': {'name': 'Vendome', 'country': 'France', 'region': 'EMEA'},
    'Vesoul': {'name': 'Vesoul', 'country': 'France', 'region': 'EMEA'},
    'Villepinte': {'name': 'Villepinte', 'country': 'France', 'region': 'EMEA'},
    'Vincennes': {'name': 'Vincennes', 'country': 'France', 'region': 'EMEA'},
    'Vittel': {'name': 'Vittel', 'country': 'France', 'region': 'EMEA'},
    'Wissembourg': {'name': 'Wissembourg', 'country': 'France', 'region': 'EMEA'},

    'Berlin': {'name': 'Berlin', 'country': 'Germany', 'region': 'EMEA'},
    'Duisburg': {'name': 'Duisburg', 'country': 'Germany', 'region': 'EMEA'},
    'FRANKFURT': {'name': 'Frankfurt', 'country': 'Germany', 'region': 'EMEA'},
    'FRANKFURT A. MAIN': {'name': 'Frankfurt', 'country': 'Germany', 'region': 'EMEA'},
    'Frankfurt am Main': {'name': 'Frankfurt', 'country': 'Germany', 'region': 'EMEA'},
    'Gerlingen': {'name': 'Gerlingen', 'country': 'Germany', 'region': 'EMEA'},
    'Hamburg': {'name': 'Hamburg', 'country': 'Germany', 'region': 'EMEA'},
    'Hanover': {'name': 'Hanover', 'country': 'Germany', 'region': 'EMEA'},
    'Munich': {'name': 'Munich', 'country': 'Germany', 'region': 'EMEA'},
    'Nuremberg': {'name': 'Nuremberg', 'country': 'Germany', 'region': 'EMEA'},
    'Stuttgart': {'name': 'Stuttgart', 'country': 'Germany', 'region': 'EMEA'},

    'BUDAPEST': {'name': 'Budapest', 'country': 'Hungary', 'region': 'EMEA'},

    'MUMBAI (MSA)': {'name': 'Mumbai', 'country': 'India', 'region': 'EMEA'},
    'BENGALURU': {'name': 'Bengaluru', 'country': 'India', 'region': 'EMEA'},

    'Jakarta': {'name': 'Jakarta', 'country': 'Indonesia', 'region': 'ASIA'},

    'DUBLIN': {'name': 'Dublin', 'country': 'Ireland', 'region': 'EMEA'},

    'Florence': {'name': 'Florence', 'country': 'Italy', 'region': 'EMEA'},
    'MILAN': {'name': 'Milan', 'country': 'Italy', 'region': 'EMEA'},
    'Milano': {'name': 'Milano', 'country': 'Italy', 'region': 'EMEA'},
    'Rome': {'name': 'Rome', 'country': 'Italy', 'region': 'EMEA'},
    'Verona': {'name': 'Verona', 'country': 'Italy', 'region': 'EMEA'},

    'TEL AVIV': {'name': 'Tel Aviv', 'country': 'Israel', 'region': 'EMEA'},

    'Abidjan Autonomous District': {
        'name': 'Abidjan Autonomous District', 'country': "Ivory Coast", 'region': 'EMEA'
    },
    'Abidjan': {'name': 'Abidjan', 'country': 'Ivory Coast', 'region': 'EMEA'},

    'TOKYO': {'name': 'Tokyo', 'country': 'Japan', 'region': 'ASIA'},
    'TOKYO APAC': {'name': 'Tokyo APAC', 'country': 'Japan', 'region': 'ASIA'},

    'Almaty': {'name': 'Almaty', 'country': 'Kazakhstan', 'region': 'ASIA'},

    'LUXEMBOURG': {'name': 'Luxembourg', 'country': 'Luxembourg', 'region': 'EMEA'},
    'Luxembourg City': {'name': 'Luxembourg', 'country': 'Luxembourg', 'region': 'EMEA'},
    'Luxemburg': {'name': 'Luxembourg', 'country': 'Luxembourg', 'region': 'EMEA'},

    'CDMX': {'name': 'Mexico City', 'country': 'Mexico', 'region': 'AMERICAS'},
    'MEXICO CITY': {'name': 'Mexico City', 'country': 'Mexico', 'region': 'AMERICAS'},
    'Ciudad De Mexico': {'name': 'Mexico City', 'country': 'Mexico', 'region': 'AMERICAS'},
    'MEXICO': {'name': 'Mexico City', 'country': 'Mexico', 'region': 'AMERICAS'},

    'Casablanca': {'name': 'Casablanca', 'country': 'Morocco', 'region': 'EMEA'},

    'Amsterdam': {'name': 'Amsterdam', 'country': 'Netherlands', 'region': 'EMEA'},

    'Callao Region': {'name': 'Callao Region', 'country': 'Peru', 'region': 'AMERICAS'},
    'Lima': {'name': 'Lima', 'country': 'Peru', 'region': 'AMERICAS'},

    'WARSAW': {'name': 'Warsaw', 'country': 'Poland', 'region': 'EMEA'},
    'Warszawa': {'name': 'Warsaw', 'country': 'Poland', 'region': 'EMEA'},

    'Lisbon': {'name': 'Lisbon', 'country': 'Portugal', 'region': 'EMEA'},
    'Porto': {'name': 'Porto', 'country': 'Portugal', 'region': 'EMEA'},

    'Bucharest': {'name': 'Bucharest', 'country': 'Romania', 'region': 'EMEA'},

    'SINGAPORE': {'name': 'Singapore', 'country': 'Singapore', 'region': 'ASIA'},

    'JOHANNESBURG': {'name': 'Johannesburg', 'country': 'South Africa', 'region': 'EMEA'},

    'Community of Madrid': {'name': 'Madrid', 'country': 'Spain', 'region': 'EMEA'},
    'Comunidad de Madrid': {'name': 'Madrid', 'country': 'Spain', 'region': 'EMEA'},
    'MADRID': {'name': 'Madrid', 'country': 'Spain', 'region': 'EMEA'},

    'SEOUL': {'name': 'Seoul', 'country': 'South Korea', 'region': 'ASIA'},

    'STOCKHOLM': {'name': 'Stockholm', 'country': 'Sweden', 'region': 'EMEA'},

    'Geneva': {'name': 'Geneva', 'country': 'Switzerland', 'region': 'EMEA'},
    'ZURICH': {'name': 'Zurich', 'country': 'Switzerland', 'region': 'EMEA'},
    'Zürich': {'name': 'Zurich', 'country': 'Switzerland', 'region': 'EMEA'},

    'Taipei': {'name': 'Taipei', 'country': 'Taiwan', 'region': 'ASIA'},

    'Istanbul': {'name': 'Istanbul', 'country': 'Turkey', 'region': 'EMEA'},

    'DUBAI': {'name': 'Dubai', 'country': 'UAE', 'region': 'EMEA'},

    'LONDON': {'name': 'London', 'country': 'UK', 'region': 'EMEA'},
    'GLASGOW': {'name': 'Glasgow', 'country': 'UK', 'region': 'EMEA'},

    'ADDISON': {'name': 'Addison', 'country': 'US', 'region': 'AMERICAS'},
    'ALPHARETTA': {'name': 'Alpharetta', 'country': 'US', 'region': 'AMERICAS'},
    'ATLANTA': {'name': 'Atlanta', 'country': 'US', 'region': 'AMERICAS'},
    'AUSTIN': {'name': 'Austin', 'country': 'US', 'region': 'AMERICAS'},
    'BALTIMORE': {'name': 'Baltimore', 'country': 'US', 'region': 'AMERICAS'},
    'BLOOMFIELD HILLS': {'name': 'Bloomfield Hills', 'country': 'US', 'region': 'AMERICAS'},
    'BOSTON': {'name': 'Boston', 'country': 'US', 'region': 'AMERICAS'},
    'CHANDLER': {'name': 'Chandler', 'country': 'US', 'region': 'AMERICAS'},
    'CHARLOTTE': {'name': 'Charlotte', 'country': 'US', 'region': 'AMERICAS'},
    'CHESTER': {'name': 'Chester', 'country': 'US', 'region': 'AMERICAS'},
    'Chesterbrook': {'name': 'Chesterbrook', 'country': 'United States', 'region': 'AMERICAS'},
    'CHICAGO': {'name': 'Chicago', 'country': 'US', 'region': 'AMERICAS'},
    'CHICO': {'name': 'Chico', 'country': 'US', 'region': 'AMERICAS'},
    'CINCINNATI': {'name': 'Cincinnati', 'country': 'US', 'region': 'AMERICAS'},
    'COLUMBUS': {'name': 'Columbus', 'country': 'US', 'region': 'AMERICAS'},
    'DALLAS': {'name': 'Dallas', 'country': 'US', 'region': 'AMERICAS'},
    'DALLAS METRO': {'name': 'Dallas', 'country': 'US', 'region': 'AMERICAS'},
    'DENVER': {'name': 'Denver', 'country': 'US', 'region': 'AMERICAS'},
    'EAST HARTFORD': {'name': 'Hartford', 'country': 'US', 'region': 'AMERICAS'},
    'FORT LAUDERDALE': {'name': 'Fort Lauderdale', 'country': 'US', 'region': 'AMERICAS'},
    'FORT WORTH': {'name': 'Fort Worth', 'country': 'US', 'region': 'AMERICAS'},
    'GARDEN CITY': {'name': 'Garden City', 'country': 'US', 'region': 'AMERICAS'},
    'GREENWICH': {'name': 'Greenwich', 'country': 'US', 'region': 'AMERICAS'},
    'HARTFORD': {'name': 'Hartford', 'country': 'US', 'region': 'AMERICAS'},
    'HOUSTON': {'name': 'Houston', 'country': 'US', 'region': 'AMERICAS'},
    'INDIANAPOLIS': {'name': 'Indianapolis', 'country': 'US', 'region': 'AMERICAS'},
    'IRVINE': {'name': 'Irvine', 'country': 'US', 'region': 'AMERICAS'},
    'JACKSONVILLE': {'name': 'Jacksonville', 'country': 'US', 'region': 'AMERICAS'},
    'JERSEY CITY': {'name': 'Jersey City', 'country': 'US', 'region': 'AMERICAS'},
    'LOS ANGELES': {'name': 'Los Angeles', 'country': 'US', 'region': 'AMERICAS'},
    'MIAMI': {'name': 'Miami', 'country': 'US', 'region': 'AMERICAS'},
    'NEW YORK': {'name': 'New York', 'country': 'US', 'region': 'AMERICAS'},
    'NYC METRO': {'name': 'New York', 'country': 'US', 'region': 'AMERICAS'},
    'NEWPORT BEACH': {'name': 'Newport Beach', 'country': 'US', 'region': 'AMERICAS'},
    'PALM BEACH GARDENS': {'name': 'Palm Beach Gardens', 'country': 'US', 'region': 'AMERICAS'},
    'PALO ALTO': {'name': 'Palo Alto', 'country': 'US', 'region': 'AMERICAS'},
    'PASADENA': {'name': 'Pasadena', 'country': 'US', 'region': 'AMERICAS'},
    'PENNINGTON': {'name': 'Pennington', 'country': 'US', 'region': 'AMERICAS'},
    'PHILADELPHIA': {'name': 'Philadelphia', 'country': 'US', 'region': 'AMERICAS'},
    'PHOENIX': {'name': 'Phoenix', 'country': 'US', 'region': 'AMERICAS'},
    'PLANO': {'name': 'Plano', 'country': 'US', 'region': 'AMERICAS'},
    'PROVIDENCE': {'name': 'Providence', 'country': 'US', 'region': 'AMERICAS'},
    'PURCHASE': {'name': 'Purchase', 'country': 'US', 'region': 'AMERICAS'},
    'RICHARDSON': {'name': 'Richardson', 'country': 'US', 'region': 'AMERICAS'},
    'RICHMOND': {'name': 'Richmond', 'country': 'US', 'region': 'AMERICAS'},
    'SAN DIEGO': {'name': 'San Diego', 'country': 'US', 'region': 'AMERICAS'},
    'SAN FRANCISCO': {'name': 'San Francisco', 'country': 'US', 'region': 'AMERICAS'},
    'SAN JOSE': {'name': 'San Jose', 'country': 'US', 'region': 'AMERICAS'},
    'SEATTLE': {'name': 'Seattle', 'country': 'US', 'region': 'AMERICAS'},
    'STAMFORD': {'name': 'Stamford', 'country': 'US', 'region': 'AMERICAS'},
    'THE WOODLANDS': {'name': 'The Woodlands', 'country': 'US', 'region': 'AMERICAS'},
    'WASHINGTON': {'name': 'Washington', 'country': 'US', 'region': 'AMERICAS'},
    'WAYNE': {'name': 'Wayne', 'country': 'US', 'region': 'AMERICAS'},
    'WEST CONSHOHOCKEN': {'name': 'West Conshohocken', 'country': 'US', 'region': 'AMERICAS'},
    'WILMINGTON': {'name': 'Wilmington', 'country': 'US', 'region': 'AMERICAS'},

    'MULTIPLE': {'name': 'Multiple'},
}


COUNTRIES_MAPPING = {
    "ARGENTINA": {'country': 'Argentina', 'region': 'AMERICAS'},
    "AUSTRALIA": {'country': 'Australia', 'region': 'ASIA'},
    "CÔTE D'IVOIRE": {'country': "Ivory Coast", 'region': 'EMEA'},
    "BELGIUM": {'country': 'Belgium', 'region': 'EMEA'},
    "BRAZIL": {'country': 'Brazil', 'region': 'AMERICAS'},
    "CANADA": {'country': 'Canada', 'region': 'AMERICAS'},
    "CHINA": {'country': 'China', 'region': 'ASIA'},
    "MAINLAND CHINA": {'country': 'China', 'region': 'ASIA'},
    "FRANCE": {'country': 'France', 'region': 'EMEA'},
    "GERMANY": {'country': 'Germany', 'region': 'EMEA'},
    "HONG KONG": {'country': 'Hong Kong', 'region': 'ASIA'},
    "INDIA": {'country': 'India', 'region': 'ASIA'},
    "INDONESIA": {'country': 'Indonesia', 'region': 'ASIA'},
    "ITALY": {'country': 'Italy', 'region': 'EMEA'},
    "IVORY COAST": {'country': 'Ivory Coast', 'region': 'EMEA'},
    "KAZAKHSTAN": {'country': 'Kazakhstan', 'region': 'ASIA'},
    "LUXEMBOURG": {'country': 'Luxembourg', 'region': 'EMEA'},
    "MEXICO": {'country': 'Mexico', 'region': 'AMERICAS'},
    "MONACO": {'country': 'Monaco', 'region': 'EMEA'},
    "MOROCCO": {'country': 'Morocco', 'region': 'EMEA'},
    "NETHERLANDS": {'country': 'Netherlands', 'region': 'EMEA'},
    "PERU": {'country': 'Peru', 'region': 'EMEA'},
    "POLAND": {'country': 'Poland', 'region': 'EMEA'},
    "PORTUGAL": {'country': 'Portugal', 'region': 'EMEA'},
    "ROMANIA": {'country': 'Romania', 'region': 'EMEA'},
    "SINGAPORE": {'country': 'Singapore', 'region': 'ASIA'},
    "SPAIN": {'country': 'Spain', 'region': 'EMEA'},
    "SWITZERLAND": {'country': 'Switzerland', 'region': 'EMEA'},
    "TAIWAN": {'country': 'Taiwan', 'region': 'ASIA'},
    "TURKEY": {'country': 'Turkey', 'region': 'EMEA'},
    "UAE": {'country': 'UAE', 'region': 'EMEA'},
    "UNITED KINGDOM": {'country': 'UK', 'region': 'EMEA'},
    "UK": {'country': 'UK', 'region': 'EMEA'},
    "UNITED STATES": {'country': 'US', 'region': 'AMERICAS'},
    "USA": {'country': 'US', 'region': 'AMERICAS'},
    "UNITED STATES OF AMERICA": {'country': 'US', 'region': 'AMERICAS'},
}
